### PR TITLE
Transfer maintenance to Simon

### PR DESCRIPTION
**Pull request by Karsten1987**

### CODE REVIEW

**Comment by mossmaurice** [comment]
@Karsten1987 Thanks for the PR! 

Unfortunately, `ament_xmllint` doesn't like it:

```
Error: /home/runner/work/rmw_iceoryx/rmw_iceoryx/rmw_iceoryx_cpp/package.xml:7: element author: Schemas validity error : Element 'author': This element is not expected. Expected is ( maintainer ).
```

Could you change it to two `<maintainer>` entries and update it to your current email address? Thanks :pray: 


FYI @budrus @ralph-lange As we discussed this morning.

**Comment by Karsten1987** [comment]
Is the linter not working correctly then?
https://ros.org/reps/rep-0140.html#author-multiple allows an `author` tag in its definition.

**Comment by mjcarroll** [comment]
I believe that you need at least one <author> tag.

**Comment by mossmaurice** [comment]
@Karsten1987 Can you try swapping the lines `<author>` and `<maintainer>`? AFAIU the ordering is defined in the [XML schema](http://download.ros.org/schema/package_format2.xsd) and `<maintainer>` has to come first.

**Review by ralph-lange — APPROVED** [review]
Approved, but commit needs sign-off.

**Pull request merged**
